---
title: "Homework 1"
author: "Jeff Tilton"
date: "1/20/2019"
output:
  rmarkdown::pdf_document:
    fig_caption: yes        
    includes:  
      in_header: preamble-latex.tex
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos= "H")
```

# Intro


Jet lag is a common problem for people traveling across multiple time zones, but people can gradually adjust to the new time zone since the exposure of the shifted light schedule to their eyes can resets the internal circadian rhythm in a process called “phase shift”. Campbell and Murphy (1998) in a highly controversial study reported that the human circadian clock can also be reset by only exposing the back of the knee to light, with some hailing this as a major discovery and others challenging aspects of the experimental design. The table below is taken from a later experiment by Wright and Czeisler (2002) that re-examined the phenomenon. The new experiment measured circadian rhythm through the daily cycle of melatonin production in 22 subjects randomly assigned to one of three light treatments. Subjects were woken from sleep and for three hours were exposed to bright lights applied to the eyes only, to the knees only or to neither (control group). The effects of treatment to the circadian rhythm were measured two days later by the magnitude of phase shift (measured in hours) in each subject’s daily cycle of melatonin production. A negative measurement indicates a delay in melatonin production, a predicted effect of light treatment, while a positive number indicates an advance.


### Raw Data
|Phase Shift (h)|Control|Knees|Eyes|
|--|--|-------------|-------|
|1|0.53|0.73|-0.78|
|2|0.36|0.31|-0.86|
|3|0.20|0.03|-1.35|
|4|-0.37|-0.29|-1.48|
|5|-0.60|-0.56|-1.52|
|6|-0.64|-0.96|-2.04|
|7|-0.68|-1.61|-2.83|
|8|-1.27|||


### ANOVA Table Part a
|Source|DF|SS|MS|F-Statistic|p-value|
|--|--|-------------|-------|--|--|
|Treatments|2|7.2244|3.6122|7.28|0.004|
|Error|19|9.415|0.496|
|Total|21|16.6|


### Means Part b
$$
\begin{aligned}
Control&= \mu_1 = -0.31\\ 
Knees&= \mu_2 = -0.34\\
Eyes&= \mu_3 = -1.55
\end{aligned}
$$

### Hypotheses Part c

$$H_o: \mu_1 = \mu_2 = \mu3$$
$$H_A: \textrm{There are diferences between } \mu_1,\textrm{ } \mu_2,\textrm{ }  \mu3. $$


The F-Statistic is much greater than 1 and the p-value<<.05 so we can reject the null hypothesis that these means are equal.  Therefore we can conclude that light treatment has the potential to reset the internal circadian rhythm.  

